### ISSUE TITLE
Wrong perl used in test suite?

### ISSUE THREAD

**Issue by eserte** [vti/cpan-audit#6]
The test suite fails on almost all of my smokers. The test log starts with:

```
Output from './Build test':


    #   Failed test at t/cli.t line 12.
    #                   'Can't locate Module/CPANfile.pm in @INC (you may need to install the Module::CPANfile module) (@INC contains: /usr/home/eserte/.cpan/build/2018101621/CPAN-Audit-0.06-2/blib/arch /usr/home/eserte/.cpan/build/2018101621/CPAN-Audit-0.06-2/blib/lib /usr/local/lib/perl5/site_perl/mach/5.20 /usr/local/lib/perl5/site_perl /usr/local/lib/perl5/5.20/mach /usr/local/lib/perl5/5.20 /usr/local/lib/perl5/site_perl/5.20 /usr/local/lib/perl5/site_perl/5.20/mach .) at /usr/home/eserte/.cpan/build/2018101621/CPAN-Audit-0.06-2/blib/lib/CPAN/Audit/Discover/Cpanfile.pm line 4.
    # BEGIN failed--compilation aborted at /usr/home/eserte/.cpan/build/2018101621/CPAN-Audit-0.06-2/blib/lib/CPAN/Audit/Discover/Cpanfile.pm line 4.
    # Compilation failed in require at /usr/home/eserte/.cpan/build/2018101621/CPAN-Audit-0.06-2/blib/lib/CPAN/Audit/Discover.pm line 4.
    # BEGIN failed--compilation aborted at /usr/home/eserte/.cpan/build/2018101621/CPAN-Audit-0.06-2/blib/lib/CPAN/Audit/Discover.pm line 4.
    # Compilation failed in require at /usr/home/eserte/.cpan/build/2018101621/CPAN-Audit-0.06-2/blib/lib/CPAN/Audit.pm line 6.
    # BEGIN failed--compilation aborted at /usr/home/eserte/.cpan/build/2018101621/CPAN-Audit-0.06-2/blib/lib/CPAN/Audit.pm line 6.
    # Compilation failed in require at script/cpan-audit line 7.
    # BEGIN failed--compilation aborted at script/cpan-audit line 7.
    # '
    #     doesn't match '(?^ms:Usage:.*cpan-audit)'
    # Looks like you failed 1 test of 3.
```

The presence of /usr/local/lib/.../mach directories in `@INC` suggests that the system perl is used here, not the perl used for building and testing the distribution.

Probably two errors here:
* cpan-audit has `/usr/bin/env perl` as the shebang. While this is convenient in some situations, it also means that EUMM and MB won't replace the shebang with the perl used in the current build
* it's probably better to use blib/script/cpan-audit in the tests, as this one has the correct shebang (if the first item is solved) (but unfortunately this does not apply to Windows or other shebang-less systems)

**Comment by eserte** [comment]
It's legal to run the build & test process with a perl which is accessed by full path, or using the perl5.X.Y name. So depending on `$PATH` won't work everywhere. Using `$^X` is a much better solution.

**Comment by vti** [comment]
Looks like it's working now http://www.cpantesters.org/cpan/report/55fff8de-d18f-11e8-84a2-e79d9d6df609.

Thanks for the heads up.

**Comment by eserte** [comment]
Yes, looks good now.
