### ISSUE TITLE
Please don't hide CPAN::Audit::DB from the PAUSE indexer

### ISSUE THREAD

**Issue by charsbar** [vti/cpan-audit#7]
Because CPAN::Audit::DB is not listed in 02packages.details.txt, people can't find it via MetaCPAN, or can't install it via cpanm (through a used module list that is created by a scanning tool like Perl::PrereqScanner::NotQuiteLite, which can't associate it with CPAN-Audit distribution, too). You can't also prevent someone from making another distribution with CPAN::Audit::DB that does something different from yours.

I don't see any reason to hide it becauase it lives in an independent file with only one package. Could you expose it to PAUSE?

**Comment by vti** [comment]
It is autogenerated and is a very big file.

**Comment by charsbar** [comment]
CPAN::Audit::DB is not the only autogenerated module. See common::sense for example, which is generated by [sense.pm.PL](https://metacpan.org/source/MLEHMANN/common-sense-3.74/sense.pm.PL) when you run Makefile.PL, but it's listed in 02packages.details. Or see [Number-Phone-UK-DetailedLocations distribution](https://metacpan.org/source/DCANTRELL/Number-Phone-UK-DetailedLocations-1.5/lib/Number/Phone/UK), which has also an autogenerated module that is much bigger than yours (35.57M, and of course MetaCPAN refuses to show it inline), which is also listed in 02packages.details. It doesn't really matter for PAUSE (or other toolchain modules) how big a module is, because PAUSE and toolchains only need to know what belongs to what (or to whom), and with what version. It may take a little longer to parse version etc, and it may be better not to keep all the old distributions because of the size, but that's all.

If you really care about the module size, there's an option to fetch distribution versions with MetaCPAN API when necessary. By doing so, you don't need to keep all the versions in it. Of course you can cache the fetched data, and ditch the cache when it's too old. As there are only several dozens of distribution that have CVEs, it's not that expensive to fetch their information from MetaCPAN, say, comparing with a distribution with hundreds of dependencies.

**Comment by vti** [comment]
Ok, i will release it.

**Comment by charsbar** [comment]
Thanks!
